[default]
src = "contracts"
out = "out"
lib = "lib"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID"
mainnet = "https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"
